### PR TITLE
Add fastlane for F-Droid

### PR DESCRIPTION
**Pull request by linsui**
F-Droid will fetch metadata from fastlane structure.

### CODE REVIEW

**Comment by HenryQuan** [comment]
Screenshots are empty. Are they supported to be empty?

**Comment by linsui** [comment]
Sorry, I messed up the symlink. It should work now.

**Comment by HenryQuan** [comment]
The symlink doesn't seem to work on Windows but I think the path is correct now. I will merge now.

**Comment by linsui** [comment]
Yes, it needs some tricks to make the symlink work on Windows. Another solution is moving those svreenshots to fastlane and point to them in readme. Thanks!

**Pull request merged**
